### ISSUE TITLE
Move the disable hyperchat button to the youtube menu

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/chat#2]
The ``Disable HyperChat`` button is an eyesore in the youtube chat.

![image](https://user-images.githubusercontent.com/50760816/111044873-08f3e480-8400-11eb-9d5c-6c327270eebd.png)

It should be moved to the top of the triple dot menu.

![image](https://user-images.githubusercontent.com/50760816/111044908-2b85fd80-8400-11eb-8444-22c8c1a8ba83.png)

**Comment by KentoNishi** [comment]
Button is now shorter, putting it in there turned out to be more difficult than expected due to Youtube's framework being jank af
