### ISSUE TITLE
Adjust name text colors for better contrast

### ISSUE THREAD

**Issue by ChrRubin** [LiveTL/chat#4]
First 2 columns of the tables are the suggested color codes along with example images, while the 3rd column shows the colors that are currently being used for comparison.

## Moderator
| Dark theme: #A0BDFC | Lite theme: #2441C0 | Original |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/20059164/116666256-5555ac80-a9cd-11eb-9eb6-c9c240702b25.png) | ![image](https://user-images.githubusercontent.com/20059164/116666527-9ea5fc00-a9cd-11eb-89c6-e06b267eae4e.png) |![image](https://user-images.githubusercontent.com/20059164/116668206-ae264480-a9cf-11eb-8cd9-75d54cdf701b.png)|

## Channel Owner
|Dark theme: #FFD600|Lite theme: #866518|Original|
|---|---|---|
|![image](https://user-images.githubusercontent.com/20059164/116666786-f80e2b00-a9cd-11eb-9768-5a7f773701c4.png)|![image](https://user-images.githubusercontent.com/20059164/116666802-fd6b7580-a9cd-11eb-983e-7e6ae4a4ad69.png)|![image](https://user-images.githubusercontent.com/20059164/116668345-e88fe180-a9cf-11eb-8149-0737b7c7b17a.png)|

Lite theme color looks a bit weird, but not much we can do about yellow on white.

## Member
|Dark theme: #04B301|Lite theme: #0E5D10|Original|
|---|---|---|
|![image](https://user-images.githubusercontent.com/20059164/116667321-a31ee480-a9ce-11eb-8d5c-54f3570b29e5.png)|![image](https://user-images.githubusercontent.com/20059164/116686431-5fd07000-a9e6-11eb-9920-1f450b69b3c5.png)|![image](https://user-images.githubusercontent.com/20059164/116668541-1b39da00-a9d0-11eb-9f46-6f7c4d4f6196.png)|

**Comment by KentoNishi** [comment]
thx for the table, it's super helpful

**Comment by KentoNishi** [comment]
![image](https://user-images.githubusercontent.com/38841491/116762491-71f2e400-a9cf-11eb-96d8-8d0c0ed95fa3.png)
![image](https://user-images.githubusercontent.com/38841491/116762494-73241100-a9cf-11eb-968c-f4e7fb37dd9b.png)
