### ISSUE TITLE
Chat doesn't load if you have HC enabled on extension load

### ISSUE THREAD

**Issue by Hughp135** [LiveTL/chat#8]
If you have enabled HC, and open LiveTL, the chat _never_ loads unless you disable/re-enable hyperchat.

The cause is probably that it doesn't initiate http requests to `/get_live_chat` if you open LiveTL with it enabled.

To reproduce this bug, enable HC, then reload the page. Chat messages don't come in 100% of the time for me.

Possible solution would be to delay HC for a few seconds before enabling it, to give time for the get_live_chat requests to start coming in? or otherwise figure out a way to manually trigger it.

The easiest solution would be to always start with hyperchat disabled, requiring the user to manually click enable HC every time. (obviously not ideal, but should be foolproof)

**Comment by Hughp135** [comment]
Actually this bug doesn't appear to be happening today, I wonder why it happened yesterday :joy:

**Comment by KentoNishi** [comment]
it's usually cuz youtube is being stupid and it fcks up our interception for unknown reasons. closing for now, reopen if it happens agane
